vim.keymap.set('n', '<leader>ps', ":lua require('telescope.builtin').grep_string({ search = vim.fn.input(\"Grep for > \")})<CR>")
vim.keymap.set('n', '<leader>bd', ':BufferClose<CR>')
vim.keymap.set('n', '<leader>b,', ':BufferPrevious<CR>')
vim.keymap.set('n', '<leader>b.', ':BufferNext<CR>')
vim.keymap.set('n', '<leader>b1', ':BufferGoto 1<CR>')
vim.keymap.set('n', '<leader>b2', ':BufferGoto 2<CR>')
vim.keymap.set('n', '<leader>b3', ':BufferGoto 3<CR>')
vim.keymap.set('n', '<leader>b4', ':BufferGoto 4<CR>')
vim.keymap.set('n', '<leader>b5', ':BufferGoto 5<CR>')
vim.keymap.set('n', '<leader>b6', ':BufferGoto 6<CR>')
vim.keymap.set('n', '<leader>b7', ':BufferGoto 7<CR>')
vim.keymap.set('n', '<leader>b8', ':BufferGoto 8<CR>')
vim.keymap.set('n', '<leader>b9', ':BufferGoto 9<CR>')
vim.keymap.set('n', '<leader>ft', ':NvimTreeToggle<CR>')
vim.keymap.set('n', '<leader>gb', ':Git blame<CR>')
vim.keymap.set('n', '<leader>fo', ':NvimTreeFindFile<CR>')
